### ISSUE TITLE
Lily pads have no texture

### ISSUE THREAD

**Issue by Lolothepro** [FabianMPunkt/Nautilus3D#15]
### Game Version

Vanilla 1.20.5

### List of all loaded packs

Nautilus3D only

### Describe your issue

Lily pads have no texture

**Comment by FabianMPunkt** [comment]
Hey thanks for reporting!
Turns out Vanilla Minecraft doesn't like uppercase letters in filenames. It works just fine with Fabric/Sodium.
![image](https://github.com/FabianMPunkt/Nautilus3D/assets/78741736/3db17073-b921-4215-9f0f-6fceacd6b299)
The fix will be in the next update. in the mean time you can replace the affected files:
https://github.com/FabianMPunkt/Nautilus3D/commit/81917517e5270296e221e77d2b0420f4993b7422
